[general]
language = "tr"
fullscreen = false
window_width = 1280
window_height = 720
vsync = true

[audio]
sfx_volume = 80
music_volume = 70
sfx_enabled = true
music_enabled = true

[gameplay]
auto_save = true
aim_guide_line = true
