[_settings]
gravity = 9.81 # or generally 10
bounce_damping = 0.4
danger_time_seconds = 3
max_spawn_value = 256

[objects.object_1]
id = "object_1"
name = "object_1_name"
value = 1
mass = 1.0
score = 2
color_hex = "eee4da"
color_rgb = "238, 228, 218"
sprite = "project-a/game/gfx/2d/objects/object_1.png"

[objects.object_2]
id = "object_2"
name = "object_2_name"
value = 2
mass = 1.4
score = 4
color_hex = "ede0c8"
color_rgb = "237, 224, 200"
sprite = "project-a/game/gfx/2d/objects/object_2.png"

[objects.object_3]
id = "object_3"
name = "object_3_name"
value = 4
mass = 1.9
score = 8
color_hex = "f2b179"
color_rgb = "242, 177, 121"
sprite = "project-a/game/gfx/2d/objects/object_3.png"

[objects.object_4]
id = "object_4"
name = "object_4_name"
value = 8
mass = 2.5
score = 16
color_hex = "f59563"
color_rgb = "245, 149, 99"
sprite = "project-a/game/gfx/2d/objects/object_4.png"

[objects.object_5]
id = "object_5"
name = "object_5_name"
value = 16
mass = 3.2
score = 32
color_hex = "f67c5f"
color_rgb = "246, 124, 95"
sprite = "project-a/game/gfx/2d/objects/object_5.png"

[objects.object_6]
id = "object_6"
name = "object_6_name"
value = 32
mass = 4.0
score = 64
color_hex = "f65e3b"
color_rgb = "246, 94, 59"
sprite = "project-a/game/gfx/2d/objects/object_6.png"

[objects.object_7]
id = "object_7"
name = "object_7_name"
value = 64
mass = 4.9
score = 128
color_hex = "edcf72"
color_rgb = "237, 207, 114"
sprite = "project-a/game/gfx/2d/objects/object_7.png"

[objects.object_8]
id = "object_8"
name = "object_8_name"
value = 128
mass = 5.9
score = 256
color_hex = "edcc61"
color_rgb = "237, 204, 97"
sprite = "project-a/game/gfx/2d/objects/object_8.png"

[objects.object_9]
id = "object_9"
name = "object_9_name"
value = 256
mass = 6.8
score = 512
color_hex = "edc850"
color_rgb = "237, 200, 80"
sprite = "project-a/game/gfx/2d/objects/object_9.png"

[objects.object_10]
id = "object_10"
name = "object_10_name"
value = 512
mass = 7.7
score = 1024
color_hex = "edc53f"
color_rgb = "237, 197, 63"
sprite = "project-a/game/gfx/2d/objects/object_10.png"

[objects.object_11]
id = "object_11"
name = "object_11_name"
value = 1024
mass = 8.8
score = 2048
color_hex = "edc22e"
color_rgb = "237, 194, 46"
sprite = "project-a/game/gfx/2d/objects/object_11.png"

[objects.object_12]
id = "object_12"
name = "object_12_name"
value = 2048
mass = 9.7
score = 4096
color_hex = "3c3a32"
color_rgb = "60, 58, 50"
sprite = "project-a/game/gfx/2d/objects/object_12.png"
